apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: NodePort
  ports:
    - port: 8000
      nodePort: 30500
      targetPort: 8000
      protocol: TCP
  selector:
    app: django
