apiVersion: v1
kind: Pod
metadata:
  name: django-pod
  labels:
    app: django
spec:
  containers:
    - name: django-container
      image: kthuang15/webapi:latest
      ports:
        - containerPort: 8000


