version: "3.8"
services:
  webserver:
    build: ./nginx
    image: nginx:latest
    volumes:
      - "./nginx/:/usr/share/nginx/html"
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8080:80"
    container_name: nginx_server
  webapi:
    build: ./django
    image: django:latest
    volumes:
      - ./django:/app
    ports:
      - "8001:8000"
    container_name: django_api
    # command: tail -f /dev/null
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    stdin_open: true
    tty: true

