apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-container
      image: kthuang15/webserver:latest
      ports:
        - containerPort: 80
  #     volumeMounts:
  #       - name: html
  #         mountPath: /usr/share/nginx/html/
  # volumes:
  #   - name: html
  #     hostPath:
  #       path: /usr/share/nginx/html/